### PR TITLE
fix: compatibility for Safari < 15.4

### LINKED ISSUE #470: Infinite loading of extension on iOS
`error	04:40:44.122704+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:40:44.120 +0200` 

^ in the console every few seconds
nothing of interest in safari inspector

before that in the console:

```
default	04:38:09.914683+0200	fileproviderd	Updating configuration of monitor <RBSProcessMonitorConfiguration| id:M672-3 qos:17 predicates:[<RBSProcessPredicate <RBSProcessBundleIdentifierPredicate "com.apple.DocumentManagerUICore.Service">>, <RBSProcessPredicate <RBSProcessBundleIdentifierPredicate "com.apple.DocumentsApp">>, <RBSProcessPredicate <RBSProcessBundleIdentifierPredicate "com.userscripts.macos.Userscripts-Extension">>] descriptor:<RBSProcessStateDescriptor| values:1 namespaces:[com.apple.frontboard.visibility]> events:0x0>
default	04:38:15.280006+0200	runningboardd	Invalidating assertion 457-4074-9658 (target:[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081]) from originator [application<com.apple.mobilesafari>:4074]
default	04:38:15.280129+0200	runningboardd	Invalidating assertion 457-4074-9660 (target:[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081]) from originator [application<com.apple.mobilesafari>:4074]
default	04:38:15.280227+0200	Userscripts-iOS-Safari-Extension	[u 85AADDAE-4546-4829-9B53-651A6E706F1E] [<private>(<private>)] Removed sole personality.
default	04:38:15.280307+0200	Userscripts-iOS-Safari-Extension	[u 85AADDAE-4546-4829-9B53-651A6E706F1E] [<private>(<private>)] host connection from pid 4074 invalidated
default	04:38:15.382330+0200	runningboardd	Removed last relative-start-date-defining assertion for process xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>
default	04:38:15.384120+0200	kernel	memorystatus: set assertion priority(0) target Userscripts-iOS-Safari-Extension:4081
default	04:38:15.384507+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Set jetsam priority to 0 [0] flag[1]
default	04:38:15.384561+0200	runningboardd	Calculated state for xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>: running-suspended (role: None)
default	04:38:15.384641+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Suspending task.
default	04:38:15.384915+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Shutdown sockets (SVC)
default	04:38:15.384952+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Error 45 setting darwin role to None: Operation not supported, falling back to setting priority
default	04:38:15.385020+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Set darwin priority to: PRIO_DARWIN_BG
default	04:38:15.385406+0200	runningboardd	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] check if suspended process is holding locks
default	04:38:15.386229+0200	SpringBoard	[xpcservice<com.userscripts.macos.Userscripts-Extension([application<com.apple.mobilesafari>:4074])>:4081] Setting process task state to: Suspended
default	04:38:15.386383+0200	mediaserverd	-CMSessionMgr- CMSessionMgrHandleApplicationStateChange: Client com.userscripts.macos.Userscripts-Extension with pid '4081' is now Background Suspended. Background entitlement: NO ActiveLongFormVideoSession: NO WhitelistedLongFormVideoApp NO
default	04:38:15.386420+0200	mediaserverd	-CMSessionMgr- CMSessionMgrHandleApplicationStateChange: Sending stop command to com.userscripts.macos.Userscripts-Extension with pid '4081' because client is background suspended and there is no AirPlay video session for it
default	04:38:15.386555+0200	mediaserverd	          SSServerImp.cpp:1250  pid 4081(Userscripts-iOS-)
error	04:38:33.871594+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:38:33.868 +0200
error	04:39:01.670711+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:39:01.669 +0200
error	04:39:24.455729+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:39:24.455 +0200
error	04:39:47.392174+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:39:47.389 +0200
error	04:40:05.164736+0200	symptomsd	COSMCtrl applyPolicyDelta unexpected absence of policy on appRecord com.userscripts.macos bg time + grace 2023-04-23 04:40:59.832 +0200  now 2023-04-23 04:40:05.163 +0200
```

### LINKED ISSUE #471: 加载脚本失败，界面持续转圈，页面报错
加载脚本失败，界面持续转圈，页面报错，请帮我解决这个问题
image

image

### PR DESCRIPTION
**Pull request by ACTCD**
fix #471 , may fix #470 

Passed the test in the iOS 15.0 simulator

### CODE REVIEW

File: src/shared/settings.js [hunk 1]
```diff
@@ -354,6 +354,11 @@ function deepFreeze(object) {
     return Object.freeze(object);
 }
 
+// compatibility polyfill for Safari < 15.4
```
Comment (quoid) [inline src/shared/settings.js:357]: If we are limiting browser versions at some point I recommend we add a note here as a reminder.
```suggestion
// @todo remove this polyfill when browser limitation is set above 15.4
// compatibility polyfill for Safari < 15.4
```

**Review by quoid — APPROVED** [review]
